CREATE TABLE restaurants (
    id bigint generated by default as identity,
    owner_id uuid not null,
    name varchar(255) not null unique,
    cuisine_type varchar(255) not null,
    city varchar(255),
    complement varchar(255),
    number varchar(255),
    state varchar(255),
    street varchar(255),
    zip_code varchar(255),
    primary key (id)
);

CREATE TABLE menu_items (
    id bigint generated by default as identity,
    restaurant_id bigint not null,
    name varchar(255) not null,
    description varchar(500),
    price numeric(38,2) not null,
    photo_path varchar(255),
    restaurant_only boolean not null,
    primary key (id),
    constraint fk_menu_items_restaurant_id foreign key (restaurant_id) references restaurants(id)
);

CREATE TABLE opening_hours_entity (
    id bigint generated by default as identity,
    restaurant_id bigint not null,
    day_of_week varchar(255) not null,
    open_hour time not null,
    close_hour time not null,
    primary key (id),
    constraint fk_opening_hours_entity_restaurant_id foreign key (restaurant_id) references restaurants(id)
);

CREATE TABLE restaurant_employees (
    restaurant_id bigint not null,
    employee_id uuid not null,
    primary key (restaurant_id, employee_id),
    constraint fk_restaurant_employees_restaurant_id foreign key (restaurant_id) references restaurants(id),
    constraint fk_restaurant_employees_employee_id foreign key (employee_id) references users(id)
);
